[package]
name = "rust-rl"
version = "0.1.0"
authors = ["MaoHuPi <jhou5846@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = "1.0.193"
serde_json = "1.0.108"
